name: floward_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^8.1.4
  # Functional programming
  dartz: ^0.10.1
  # Dependency injection
  get_it: ^7.6.7
  # Value equality
  equatable: ^2.0.5
  # Network
  http: ^1.2.0
  # Local storage
  shared_preferences: ^2.2.2
  # Internet connection checker
  internet_connection_checker: ^1.0.0
  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_flavorizr: ^2.1.0

flutter:
  uses-material-design: true
