name: floward_weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^8.1.4
  # Functional programming
  dartz: ^0.10.1
  # Dependency injection
  get_it: ^7.6.7
  # Value equality
  equatable: ^2.0.5
  # Network
  http: ^1.2.0
  # Local storage
  shared_preferences: ^2.2.2
  # Internet connection checker
  internet_connection_checker: ^1.0.0+1
  # JSON serialization
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  lottie: ^2.7.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_flavorizr: ^2.1.0
  mockito: ^5.4.4
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env.dev
    - assets/env/.env.prod
    - assets/looties/
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/weather.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#03A9F4"
  adaptive_icon_foreground: "assets/images/weather.png"

    
